package database

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
)

// Define the UserModel type.
type UserModel struct {
	DB *pgxpool.Pool
	IP IPModel
}

// Define a User struct to represent an individual user. Importantly, notice how we are
// using the json:"-" struct tag to prevent the Password and Version fields appearing in
// any output when we encode it to JSON. Also notice that the Password field uses the
// custom password type defined below.
type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  password  `json:"-"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// LoginAttempt represents a record from the login_attempts table.
// This table tracks failed login attempts per user and IP for security and rate limiting.
type LoginAttempt struct {
	ID          int64        `json:"id"`           // Unique attempt ID (primary key, auto-generated)
	UserID      int64        `json:"user_id"`      // Foreign key reference to users.id
	IP          string       `json:"ip"`           // IP address of the login attempt (defaults to '0.0.0.0')
	LastAttempt time.Time    `json:"last_attempt"` // Timestamp of the last attempt (defaults to NOW())
	Attempts    int64        `json:"attempts"`     // Number of failed attempts in the current window
	BannedUntil sql.NullTime `json:"banned_until"` // Timestamp until which the user/IP is banned (nullable)
	Bans        int64        `json:"bans"`         // Number of times this user/IP has been banned
}

// Create a custom password type which is a struct containing the plaintext and hashed
// versions of the password for a user. The plaintext field is a *pointer* to a string,
// so that we're able to distinguish between a plaintext password not being present in
// the struct at all, versus a plaintext password which is the empty string "".
type password struct {
	plaintext *string
	hash      []byte
}

// The Set() method calculates the bcrypt hash of a plaintext password, and stores both
// the hash and the plaintext versions in the struct.
func (p *password) Set(plaintextPassword string) error {
	hash, err := bcrypt.GenerateFromPassword([]byte(plaintextPassword), 12)
	if err != nil {
		return err
	}

	p.plaintext = &plaintextPassword
	p.hash = hash

	return nil
}

// The Matches() method checks whether the provided plaintext password matches the
// hashed password stored in the struct, returning true if it matches and false
// otherwise.
func (p *password) Match(plaintextPassword string) (bool, error) {
	err := bcrypt.CompareHashAndPassword(p.hash, []byte(plaintextPassword))
	if err != nil {
		switch {
		case errors.Is(err, bcrypt.ErrMismatchedHashAndPassword):
			return false, nil
		default:
			return false, err
		}
	}
	return true, nil
}

// Insert a new record in the database for the user. Note that the id, created_at and
// fields are all automatically generated by our database, so we use the
// RETURNING clause to read them into the User struct after the insert.
func (m UserModel) Insert(user *User) (int64, error) {
	query := `
                INSERT INTO users (name, email, password_hash)
                VALUES ($1, $2, $3)
                RETURNING id`

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	args := []any{user.Name, user.Email, user.Password.hash}

	err := m.DB.QueryRow(ctx, query, args...).Scan(&user.ID)
	if err != nil {
		return 0, err
	}

	return user.ID, nil
}

// Retrieve the User details from the database based on the user's email address.
// Because we have a UNIQUE constraint on the email column, this SQL query will only
// return one record (or none at all, in which case we return a ErrRecordNotFound error).
func (m UserModel) GetByEmail(email string) (*User, error) {
	query := `
                SELECT id, name, email, password_hash, created_at, updated_at
                FROM users
                WHERE email = $1`

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	var user User

	err := m.DB.QueryRow(ctx, query, email).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.Password.hash,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return nil, ErrRecordNotFound
		default:
			return nil, err
		}
	}

	return &user, nil
}

// Retrieve the User details from the database based on the user's id.
// Because we have a UNIQUE constraint on the id column, this SQL query will only
// return one record (or none at all, in which case we return a ErrRecordNotFound error).
func (m UserModel) GetByID(userID int64) (*User, error) {
	query := `
                SELECT id, name, email, password_hash, created_at, updated_at
                FROM users
                WHERE id = $1`
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	var user User

	err := m.DB.QueryRow(ctx, query, userID).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.Password.hash,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return nil, ErrRecordNotFound
		default:
			return nil, err
		}
	}

	return &user, nil
}

// Update the details for a specific user.
func (m UserModel) Update(user *User) error {
	query := `
                UPDATE users
                SET name = $1, email = $2, password_hash = $3
                WHERE id = $4`

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	args := []any{
		user.Name,
		user.Email,
		user.Password.hash,
		user.ID,
	}

	_, err := m.DB.Exec(ctx, query, args...)
	if err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return ErrEditConflict
		default:
			return err
		}
	}
	return nil
}

// UpdatePassword updates only the password_hash field for a specific user,
// identified by their user ID. It returns an error if the user is not found
// or if any other database error occurs.
func (m UserModel) UpdatePassword(user *User) error {
	query := `
        UPDATE users
        SET password_hash = $1
        WHERE id = $2`

	// Create a context with a 3-second timeout to ensure the query doesn't hang.
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	// Execute the update query and scan the returned ID to confirm the update.
	_, err := m.DB.Exec(ctx, query, user.Password.hash, user.ID)
	if err != nil {
		switch {
		// If no rows were returned, the user does not exist.
		case errors.Is(err, sql.ErrNoRows):
			return ErrRecordNotFound
		// Any other error is returned as-is.
		default:
			return err
		}
	}

	// Return nil if everything was successful.
	return nil
}

// LogAttempt logs a user's login attempt into the login_attempts table.
// It inserts a new record with the provided userID, IP, and attempts, bans count.
// Returns the generated attempt ID or an error.
func (m UserModel) LogAttempt(userID int64, ip string, attempts, bans int64) (attemptID int64, err error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	query := `
		INSERT INTO login_attempts (
			user_id, 
			ip,
			attempts,
			bans
		) VALUES ($1, $2, $3, $4)
		RETURNING id`

	args := []any{userID, ip, attempts, bans}

	err = m.DB.QueryRow(ctx, query, args...).Scan(&attemptID)
	if err != nil {
		return 0, err
	}

	return attemptID, nil
}

// GetLoginAttempt retrieves the most recent login attempt record for a specific user and IP.
// It fetches the record with the latest last_attempt timestamp.
func (m UserModel) GetLoginAttempt(userID int64, ip string) (*LoginAttempt, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	query := `
		SELECT id, user_id, host(ip), last_attempt, attempts, banned_until, bans
		FROM login_attempts
		WHERE user_id = $1 AND ip = $2
		ORDER BY last_attempt DESC
		LIMIT 1`

	args := []any{userID, ip}

	var attempt LoginAttempt
	err := m.DB.QueryRow(ctx, query, args...).Scan(
		&attempt.ID,
		&attempt.UserID,
		&attempt.IP,
		&attempt.LastAttempt,
		&attempt.Attempts,
		&attempt.BannedUntil,
		&attempt.Bans,
	)
	if err != nil {
		// If no rows found (pgx.ErrNoRows), treat it as "ok" - no previous attempt exists.
		// Return nil attempt and nil error to indicate success with no data.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		// For all other errors (e.g., connection issues), return the error.
		return nil, err
	}

	return &attempt, nil
}

// UpdateLoginAttempt updates the attempts, banned_until, and bans fields for a specific login attempt record by its ID.
func (m UserModel) UpdateLoginAttempt(attemptID int64, attempts int64, bannedUntil time.Time, bans int64) error {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	query := `
		UPDATE login_attempts
		SET attempts = $2, banned_until = $3, bans = $4
		WHERE id = $1`

	args := []any{attemptID, attempts, bannedUntil, bans}

	_, err := m.DB.Exec(ctx, query, args...)
	if err != nil {
		return err
	}

	return nil
}

// ResetAllLoginAttempt resets the attempts, banned_until, and bans fields for a specific login attempt record
// identified by attemptID and associated userID. This ensures only the correct user's attempt is reset.
// If no matching record is found (no rows affected), it returns nil (considered "ok" with no action taken).
// Returns an error for any database issues.
func (m UserModel) ResetAllLoginAttempt(userID, attemptID int64) error {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	query := `
		UPDATE login_attempts
		SET attempts = 0, banned_until = NULL, bans = 0
		WHERE id = $1 AND user_id = $2`

	args := []any{attemptID, userID}

	_, err := m.DB.Exec(ctx, query, args...)
	if err != nil {
		return err
	}

	return nil
}

// ClearLoginAttemptBan removes the temporary ban (banned_until) for a specific login attempt and user.
func (m UserModel) ClearLoginAttemptBan(attemptID, userID int64) error {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	query := `
        UPDATE login_attempts
        SET banned_until = NULL
        WHERE id = $1 AND user_id = $2`

	args := []any{attemptID, userID}

	_, err := m.DB.Exec(ctx, query, args...)
	if err != nil {
		return err
	}

	return nil
}
