CREATE TABLE "blog_posts" (
	"id" SERIAL NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"title" VARCHAR(255) NOT NULL UNIQUE,
	"description" VARCHAR(255),
	"content" TEXT NOT NULL,
	"slug" VARCHAR(255) NOT NULL UNIQUE,
	"is_published" BOOLEAN NOT NULL DEFAULT TRUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
